package com.icc.cricket.common;

public enum CricketSeries {
    ICC_MENS_WORLD_CUP, ICC_WOMEN_WORL_CUP, ICC_MENS_T20_WORLD_CUP, ICC_WOMEN_T20_WORLD_CUP,
    ICC_CHAMPIONS_TROPHY, ASHESH_SERIES, ASIA_CUP
}
